import Head from 'next/head'
import { useTheme } from 'styled-components'
import { Text } from '../components/form/text'
import { Column, Row } from '../styles/styles/home';
import { Container, Title } from '../styles/styles/home';

export default function Home() {
  const theme = useTheme();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>
          Hello, I'm a
          <Text title="  Front-End" size={38} color={theme.blue_100} weight='bold' />
          Developer!
        </Title>

        <Text title="Hello, I'm Gabriel, Front-End Developer and Freelancer." size={16} top={10} weight='500' />
        <Text title="I help brands turn their ideas into high-quality products." size={16} weight='500' />

      </Container>
    </>
  )
}
